services:
  - type: web
    name: restaurant-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_TOKEN
        sync: false
      - key: TWILIO_FROM
        value: whatsapp:+14155238886
      - key: WHATSAPP_TO
        value: whatsapp:+972507557559
